### PR TITLE
k-bucket@3

### PR DESCRIPTION
**Pull request by feross**
Performance improvements to .distance() in this version but API changes too...

**PR depends on https://github.com/mafintosh/k-rpc/pull/4 being merged first.**

### CODE REVIEW

**Comment by feross** [comment]
PR depends on https://github.com/mafintosh/k-rpc/pull/4 being merged first.

**Comment by mafintosh** [comment]
i've merged and released the pr you sent for k-rpc. we should probably force bump the semver in pkg json

**Comment by feross** [comment]
K, will do

**Comment by feross** [comment]
Bumped. Let's see if the tests pass now.

**Comment by mafintosh** [comment]
rolling the 🎲

**Comment by feross** [comment]
7.2.0

**Pull request merged**
