### PR TITLE
WIP: Updating current impl using k-rpc

### PR DESCRIPTION
**Pull request by mafintosh**
Feross and I spent most of last week at CCC in Hamburg discussing how we could make the DHT module faster / easier to maintain. This is a WIP PR of our findings.

We've split out the low-level networking logic into a new module called [k-rpc](https://github.com/mafintosh/k-rpc) to isolate that in a stable module with a stable api. The k-rpc module doubles the current concurrency factor to 16 as that made initial discovery a lot faster. It also builds the internal routing table in the background, yielding traffic to any ongoing lookups to reduce latency quite a bit. The end result is that lookups are now *a lot* faster (on my macbook finding the first peer went from >10s to <1s, YMMV).

Once this PR passes the current test suite we'll merge it in.

### CODE REVIEW

**Comment by feross** [comment]
:+1:

**Comment by karissa** [comment]
+1 great work!

**Comment by mafintosh** [comment]
@feross tests seem to be passing now. ready for review

**Comment by mafintosh** [comment]
the breaking changes should be documented in the readme. mostly infoHash is always a buffer now and peers/nodes are `{host: host, port: port}` instead of strings

**Comment by maxogden** [comment]
PUBLISH ZEE MODULE!

**Comment by feross** [comment]
But I'm le tired

**Comment by feross** [comment]
Okay, I had a nap. FIRED ZE MISSILES in version 6.0.0.

**Pull request merged**
