### PR TITLE
from.host -> from.address

### PR DESCRIPTION
**Pull request by galeksandrp**

### CODE REVIEW

**Comment by feross** [comment]
Why is this necessary?

**Comment by galeksandrp** [comment]
I don't see host property when running example from readme.

**Comment by feross** [comment]
@mafintosh Any ideas what's going on here?

**Comment by Aaron1011** [comment]
@feross: Based on the [drgam docs](https://nodejs.org/api/dgram.html#dgram_event_message), it doesn't look like the `host` property will ever be set - only `address`, `family`, and `port` will be.

**Comment by feross** [comment]
Okay, I'll merge this.

@mafintosh - why do we have references to both `.host` and `.address` in the codebase?

**Pull request merged**
