### PR TITLE
Return BEP44 values in toJSON(); remove toArray()

### PR DESCRIPTION
**Pull request by feross**
Fixes https://github.com/feross/bittorrent-dht/issues/112

This would be a major version bump.

### CODE REVIEW

**Comment by mafintosh** [comment]
how do you know if the values were mutable keys? nodeId should be part of toJSON as well

**Comment by mafintosh** [comment]
the dht's nodeId

**Comment by feross** [comment]
@mafintosh Updated the PR to include the `nodeId`. Look good now?

**Comment by mafintosh** [comment]
@feross you need to serialize the seq and signature as well

**Comment by feross** [comment]
@mafintosh What about `opts.k`? The public key.

**Comment by feross** [comment]
Updated PR

**Comment by mafintosh** [comment]
@feross oh yea that as well

**Comment by feross** [comment]
@mafintosh PR updated again :)

**Comment by feross** [comment]
@mafintosh This should be good to merge now, right?

**Comment by mafintosh** [comment]
:+1:

**Comment by feross** [comment]
7.0.0.

**Pull request merged**
